# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MeuQoelhoMQ_pb2 as MeuQoelhoMQ__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MeuQoelhoMQ_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BrokerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQueue = channel.unary_unary(
                '/MeuQoelhoMQProto.BrokerService/CreateQueue',
                request_serializer=MeuQoelhoMQ__pb2.CreateQueueRequest.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.QueueReply.FromString,
                _registered_method=True)
        self.DeleteQueue = channel.unary_unary(
                '/MeuQoelhoMQProto.BrokerService/DeleteQueue',
                request_serializer=MeuQoelhoMQ__pb2.DeleteQueueRequest.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.QueueReply.FromString,
                _registered_method=True)
        self.GetQueues = channel.unary_unary(
                '/MeuQoelhoMQProto.BrokerService/GetQueues',
                request_serializer=MeuQoelhoMQ__pb2.Empty.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.QueueListReply.FromString,
                _registered_method=True)
        self.PublishMessage = channel.unary_unary(
                '/MeuQoelhoMQProto.BrokerService/PublishMessage',
                request_serializer=MeuQoelhoMQ__pb2.PublishMessageRequest.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.MessageReply.FromString,
                _registered_method=True)
        self.PublishMessages = channel.unary_unary(
                '/MeuQoelhoMQProto.BrokerService/PublishMessages',
                request_serializer=MeuQoelhoMQ__pb2.PublishMessagesRequest.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.MessagesReply.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/MeuQoelhoMQProto.BrokerService/GetMessage',
                request_serializer=MeuQoelhoMQ__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.GetMessageReply.FromString,
                _registered_method=True)
        self.SubscribeQueue = channel.unary_stream(
                '/MeuQoelhoMQProto.BrokerService/SubscribeQueue',
                request_serializer=MeuQoelhoMQ__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=MeuQoelhoMQ__pb2.GetMessageReply.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQueue,
                    request_deserializer=MeuQoelhoMQ__pb2.CreateQueueRequest.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.QueueReply.SerializeToString,
            ),
            'DeleteQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQueue,
                    request_deserializer=MeuQoelhoMQ__pb2.DeleteQueueRequest.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.QueueReply.SerializeToString,
            ),
            'GetQueues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueues,
                    request_deserializer=MeuQoelhoMQ__pb2.Empty.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.QueueListReply.SerializeToString,
            ),
            'PublishMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMessage,
                    request_deserializer=MeuQoelhoMQ__pb2.PublishMessageRequest.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.MessageReply.SerializeToString,
            ),
            'PublishMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMessages,
                    request_deserializer=MeuQoelhoMQ__pb2.PublishMessagesRequest.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.MessagesReply.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=MeuQoelhoMQ__pb2.GetMessageRequest.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.GetMessageReply.SerializeToString,
            ),
            'SubscribeQueue': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeQueue,
                    request_deserializer=MeuQoelhoMQ__pb2.SubscribeRequest.FromString,
                    response_serializer=MeuQoelhoMQ__pb2.GetMessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeuQoelhoMQProto.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MeuQoelhoMQProto.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/CreateQueue',
            MeuQoelhoMQ__pb2.CreateQueueRequest.SerializeToString,
            MeuQoelhoMQ__pb2.QueueReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/DeleteQueue',
            MeuQoelhoMQ__pb2.DeleteQueueRequest.SerializeToString,
            MeuQoelhoMQ__pb2.QueueReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/GetQueues',
            MeuQoelhoMQ__pb2.Empty.SerializeToString,
            MeuQoelhoMQ__pb2.QueueListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/PublishMessage',
            MeuQoelhoMQ__pb2.PublishMessageRequest.SerializeToString,
            MeuQoelhoMQ__pb2.MessageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/PublishMessages',
            MeuQoelhoMQ__pb2.PublishMessagesRequest.SerializeToString,
            MeuQoelhoMQ__pb2.MessagesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/GetMessage',
            MeuQoelhoMQ__pb2.GetMessageRequest.SerializeToString,
            MeuQoelhoMQ__pb2.GetMessageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MeuQoelhoMQProto.BrokerService/SubscribeQueue',
            MeuQoelhoMQ__pb2.SubscribeRequest.SerializeToString,
            MeuQoelhoMQ__pb2.GetMessageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
